name: website

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install package dependencies
        run: npm ci
      - run: npm test
        env:
          CI: true
      - name: Semantic Release
        if: ${{ success() }}
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build
        run: npm run-script build
        env:
          PUBLIC_URL: 'https://sinyayadynya.github.io/turbo-widget'
      - name: Deploy to GitHub Pages
        if: ${{ success() }}
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: build
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
